### ISSUE TITLE
Network create and delete Unit-Tests run only in sudo

### ISSUE THREAD

**Issue by mavenugo** [socketplane/socketplane#111]
Since the Network Create and delete operations depends on netlink APIs, the tests needs to be run with sudo privileges. #109 tried to address it, but there are a few discrepancies such as ecc.Put() is called in NetworkCreate only after all the netlink apis succeed. Which seems reasonable to me. in that case, GetNetwork will fail as expected.

**Comment by dave-tucker** [comment]
if we run the tests inside a docker container, then we shouldn't have permissions issues
that container could also be the same container that is used for CI
this gives us OS portability for developers (can run IT/UT suite on any machine thanks to boot2docker) and the guarantee that tests will pass on the CI server
