### ISSUE TITLE
Create a PowerStrip plugin for Socketplane

### ISSUE THREAD

**Issue by dave-tucker** [socketplane/socketplane#137]
Refactor the PowerStrip work by @mrjana in to https://github.com/socketplane/powerstrip-socketplane

**Comment by mavenugo** [comment]
@dave-tucker I can see that the powerstrip project is kinda recommending to have adapter projects. But, am still trying to wrap my head around for such a need to have powerstrip-socketplane project when our current socketplane container serves the need well.

Even if we decide to have powerstrip-socketplane project, then I would assume the implementation of this container would depend on another container "socketplane" and they will interact via REST-APIs.

I can go either way on this. But am trying to understand the compelling need for a separate powerstrip-socketplane adapter project when the current socketplane container already works reasonably well both in wrapper and powerstrip mode.

**Comment by mrjana** [comment]
+1 @mavenugo 

@dave-tucker I don't feel that we need to separate powerstrip adapter side of the code into it's own container. On top of being an extra overhead(runtime, IPC etc) it may also complicate things in the future in terms of compatibility issues with the socketplane container.

**Comment by dave-tucker** [comment]
@mrjana @mavenugo ok guys. if you are fine bucking the trend, which appears to be having a repo named "powerstrip-*" then thats fine. You should submit a PR to the Powerstrip repo to add socketplane to the list of adapters - although it's not really an adapter it's everything. I'm not 100% sure how the other adapters are built, but I worry that this will cause confusion.

**Comment by mavenugo** [comment]
@dave-tucker I was just trying to understand the technical reason for this requirement. If it is convention, then I agree, this might be required to avoid confusion.
Powerstrip being a developer only extension framework, am trying to understand the rationale behind the requirement.

But if the powerstrip folks have a good technical reason (example : consistency for hooking multiple extensions in a chain), then we have to consider it.

@mrjana @dave-tucker If it is okay with you guys, lets raise a question and check with them.

**Comment by mrjana** [comment]
@mavenugo We should certainly get the convention issue clarified. I am not sure why all adapters should be named powerstrip-* but let's find out.

Nevertheless I feel the adapter and the actual functionality provided by the docker extension could be one and the same. Adapter is the extension and extension is the adapter. IMHO it's not a very good architecture to let container creep just for the sake of it unless there is a valid technical reason to separate them out. At the end of the day if each extension had to be implemented this way, then every extension will need at least  two (or even more) container instances and very quickly we will have an array of containers just to support the infrastructure :-)
