### ISSUE TITLE
Documentation : how to connect 2 physical servers

### ISSUE THREAD

**Issue by pilerou** [socketplane/socketplane#149]
Hi,

I posted a message on StackOverflow about the ability to connect 2 or more physical servers on which socketplane are installed.
http://stackoverflow.com/questions/28901665/socketplane-and-docker-how-to-connect-2-or-more-physical-hosts-with-each-oth

Actually, i saw #69 and  #92 issues but I think I'm not in the same usecase.

Considering i have one physical server which IP is 5.x.x.x and another which IP is 91.x.x.x.

I launched socketplane on both servers as explained in the documentation. The first one with "`BOOTSTRAP=true`" parameter and the second one with no parameter.

I had the same problem as explained on this blog 
http://arnesund.com/2015/03/06/getting-started-with-socketplane-and-docker-on-openstack-vms/

First, I wrote :
`sudo socketplane cluster bind eth0`
Problem solved even if I get an error when consul wanted to bind his port : 
> Error starting agent: Failed to start Consul server: Failed to start RPC layer: listen tcp 5.x.x.x:8300: bind: address already in use

After network creation (called *net1*) on the first server 5.x.x.x, I launched two Ubuntu containers on it. The two containers was able to ping each other (*10.100.0.2* and *10.100.0.3*).

On the second server 91.x.x.x, I also began with 
`sudo socketplane cluster bind eth0`
Then, I tried `sudo socketplane cluster join 5.x.x.x`

As I was "tailing" logs on 5.x.x.x server, I saw : 
>  2015/03/10 21:49:46 [INFO] serf: EventMemberJoin: testaca2 91.121.70.157
    2015/03/10 21:49:46 [INFO] consul: member 'testaca2' joined, marking health alive
INFO[1497] New Node joined the cluster : 91.121.70.157

==> A tear flowed down my cheek :) :+1: 

I checked my cluster was OK  on both servers :
`curl http://localhost:8500/v1/catalog/nodes`
> [{"Node":"testaca1","Address":"5.x.x.x"},{"Node":"testaca2","Address":"91.x.x.x"}]

==> Both OK !

The second server 91.x.x.x also recognised *net1* network.
` socketplane network info net1`
{
    "gateway": "10.100.0.1",
    "id": "net1",
    "subnet": "10.100.0.0/24",
    "vlan": 2
}

Then, I launched a new container by writing 
`socketplane run -n net1 -it ubuntu /bin/bash`
`ifconfig` commands on this container confirms me I was on the good cluster as IP address was *10.100.0.4*.

I tried to ping 10.100.0.2 and 10.100.0.3... 
==> But this time, I got :
> From 10.100.0.2 icmp_seq=1 Destination Host Unreachable

Same problem, when I tried to ping 91.x.x.x server container (10.100.0.4) from  5.x.x.x server containers (10.100.0.2 and 10.100.0.3) :
> From 10.100.0.4 icmp_seq=1 Destination Host Unreachable

**So I have 2 questions :**
1. How to make my first server containers talk to my second server containers ?
2. Is there functions or best practices in Socketplane to secure servers clusters (communications over SSH, authentication when a server join the cluster...) ?

Those two questions could be splitted in two issues (bug for the first one and enhancement for the second one).

Thanks for your help.

**Comment by mavenugo** [comment]
We identified a bug in the implementation on Static clustering where the VXLAN tunnel failed to get established for host discovery events (for static configurations).

@dave-tucker is working on a fix for this issue and should be in soon.

**Comment by dsampath** [comment]
+1 on this

**Comment by pilerou** [comment]
I just tried once again after updating socketplane.
It works like a charm :+1:

**Comment by mavenugo** [comment]
@pilerou Thanks for the confirmation. Please note that this is still an experimental feature. 
We have to spend more time to get this solid (such as save / restore of this config) and add more UT/ IT, etc...
PRs welcome :-)

**Comment by dsampath** [comment]
Works ! Thanks :+1:
