### ISSUE TITLE
consul cluster creation

### ISSUE THREAD

**Issue by runseb** [socketplane/socketplane#53]
Where can we see any logs regarding the multicast DNS discovery of nodes for joining a cluster ?
As well as consul lookups ?

I can start a master node just fine:

    export BOOTSTRAP=true
    socketplane install unattended

But if I try to add another node that I start manually, with no bootstrap set, then it does not seem to join the cluster.

**Comment by mavenugo** [comment]
With #69 and #115, we have this covered.
The only open issue is inter-cloud clustering without a VPC tunnel.
We are working on Consul to fix the inter-cloud clustering issues.
