### ISSUE TITLE
An "apt-get update" hangs "[Waiting for headers]" in an a socketplane created 2nd instance 

### ISSUE THREAD

**Issue by botchagalupe** [socketplane/socketplane#71]
This appears to be an intermittent issue.  It works sometimes but fails most times.  

Here is the scenario:

On a VM (e.g., socketplane-1) I create a new network.
 > sudo socketplane network create web 10.2.0.0/16

Then launch a new docker instance on that same host. 
>sudo socketplane run -n web -itd ubuntu:14.04

Then I attach to the docker instance.
>sudo socketplane attach <cid>

The run the apt-get
>sudo apt-get update 

This works fine.  

Then I jump onto a second host (e.g., socketplane-2) and do the following. 

The I launch a new docker instance on the second host. 
>sudo socketplane run -n web -itd ubuntu:14.04

Then I attach to the docker instance.
>sudo socketplane attach <cid>

The run the apt-get
>sudo apt-get update 

This is the hanging response...
```
root@e1ec329bdc1b:/# sudo apt-get update
Ign http://archive.ubuntu.com trusty InRelease
Ign http://archive.ubuntu.com trusty-updates InRelease
Ign http://archive.ubuntu.com trusty-security InRelease
Hit http://archive.ubuntu.com trusty Release.gpg
Get:1 http://archive.ubuntu.com trusty-updates Release.gpg [933 B]
Get:2 http://archive.ubuntu.com trusty-security Release.gpg [933 B]
Hit http://archive.ubuntu.com trusty Release
Ign http://archive.ubuntu.com trusty-updates Release                           
Ign http://archive.ubuntu.com trusty-security Release
100% [Waiting for headers]  
```

I could not recreate this issue running just docker w/o socketplane installed.

**Comment by botchagalupe** [comment]
A little more info... 

After further testing the "apt-get update" hang seems to only happen for the "default" network if the Vagrant created Virtualbox instance is create without "virtualbox__intnet: true".

**Comment by mavenugo** [comment]
thanks @botchagalupe for confirming the MTU issue. And yes, the scenario 
>> One way to test this scenario is to do a ping -s 1419 on a container living on a host where the containers network is not defined. It will hang every time.
forces the traffic to take the VXLAN tunnel to another host where the actual routing takes place.
VXLAN adds an overhead of 50 bytes and hence causing the issue that we see in both the ping -s and apt-get update cases.

We can try the docker daemon workaround mentioned in https://github.com/docker/docker/pull/3289 by setting a -mtu value 1400 in the daemon configuration file /etc/default/docker.io and restarting the docker service.

**Comment by mavenugo** [comment]
@botchagalupe confirmed the MTU issue by implementing the following manual workaround.
* Reduce the MTU of the internal port attached to the containers to 1400 using : **sudo ip netns exec <ns-pid> ip link set dev <ovs-internal-port-id> mtu 1400**
* Reduce the MTU of the network Gateway port to 1400 usng : **sudo ip link set dev <network-id> mtu 1400**
By reducing the MTU on both of the devices, both the Ping between the containers across Hosts and apt-get between container and external networks across the VXLAN tunnel works fine.

Will work a temporary fix to get this fixed and a more permanent fix will follow.
